### ISSUE TITLE
StatusCodeError: 400 - invalid_attachments when we have large set of test suites

### ISSUE THREAD

**Issue by KosalaiV** [test-results-reporter/reporter#144]
**test-results-reporter is not stable with handling large set of test suites.** I have around 60 test cases _(Example: 36 Json files for 36 test suites)_  and getting the below error for those. If I execute with less number of tests, all works fine. This is an highest priority, appreciate your assistance. @ASaiAnudeep @leelaprasadv 

TIA!

```
StatusCodeError: 400 - invalid_attachments
    at Object.reject (/home/vsts/work/1/s/test-automation/node_modules/phin-retry/src/index.js:184:11)
    at Object.__fetch (/home/vsts/work/1/s/test-automation/node_modules/phin-retry/src/index.js:268:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (/home/vsts/work/1/s/test-automation/node_modules/test-results-reporter/src/targets/index.js:33:5)
    at async Object.run (/home/vsts/work/1/s/test-automation/node_modules/test-results-reporter/src/commands/publish.js:31:9)
    at async /home/vsts/work/1/s/test-automation/node_modules/test-results-reporter/src/cli.js:16:7 {
  statusCode: 400,
  statusMessage: 'Bad Request',
  body: 'invalid_attachments'
}
```

**An update, it is working fine only when the** 

> "publish" prop is set to "test-summary-slim"

**Comment by KosalaiV** [comment]
Hi @ASaiAnudeep Thanks for making a progress here. Could we enhance this to accommodate more than 10 test suites? If so, this plugin would truly shine.

Thank You!

**Comment by ASaiAnudeep** [comment]
@KosalaiV , I've added a new input called `max_suites`, which is set to a default value of 10, allowing you to adjust the limit on the number of suites.

```json
{
  "name": "slack",
  "inputs": {
    "url": "<slack-incoming-webhook-url>",
    "max_suites": 20
  }
}
```
