### ISSUE TITLE
Getting ReferenceError: options is not defined when running npx test-results-reporter publish -c slack.json

### ISSUE THREAD

**Issue by kaitlin-qa** [test-results-reporter/reporter#162]
Trying to implement this in our Azure pipeline with Selenium but I'm running into an error with the initial command on our Windows 2022 agent:

```
ReferenceError: options is not defined
    at getParser (C:\Users\ContainerAdministrator\AppData\Local\npm-cache\_npx\dadb57b614912ba5\node_modules\test-results-parser\src\parsers\index.js:51:42)
    at Object.parse (C:\Users\ContainerAdministrator\AppData\Local\npm-cache\_npx\dadb57b614912ba5\node_modules\test-results-parser\src\parsers\index.js:59:18)
    at Object.parse (C:\Users\ContainerAdministrator\AppData\Local\npm-cache\_npx\dadb57b614912ba5\node_modules\test-results-parser\src\index.js:4:17)
    at processReport (C:\Users\ContainerAdministrator\AppData\Local\npm-cache\_npx\dadb57b614912ba5\node_modules\test-results-reporter\src\commands\publish.js:39:31)
    at Object.run (C:\Users\ContainerAdministrator\AppData\Local\npm-cache\_npx\dadb57b614912ba5\node_modules\test-results-reporter\src\commands\publish.js:23:11)
    at C:\Users\ContainerAdministrator\AppData\Local\npm-cache\_npx\dadb57b614912ba5\node_modules\test-results-reporter\src\cli.js:16:21
    at o.parse (C:\Users\ContainerAdministrator\AppData\Local\npm-cache\_npx\dadb57b614912ba5\node_modules\sade\lib\index.js:1:3402)
    at Object.<anonymous> (C:\Users\ContainerAdministrator\AppData\Local\npm-cache\_npx\dadb57b614912ba5\node_modules\test-results-reporter\src\cli.js:23:6)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
```

```json
{
  "targets": [
    {
      "name": "slack",
      "inputs": {
        "url": "https://hooks.slack.com/services/xxx",
        "publish": "test-summary"
      }
    }


  ],
  "results": [
    {
      "type": "VStest",
      "files": [ "**/*.trx" ]
    }
  ]
}
```

**Comment by leelaprasadv** [comment]
@kaitlin-qa 
`test-results-reporter` works with the result types mentioned here https://test-results-reporter.github.io/guides/results.html#syntax

Unfortunately, the reporter doesn't support `.trx` report files. I recommend generating the results in any of the supported report formats and it should work.
